"""Admin Table Creation

Revision ID: 0a4b92cc0b2a
Revises: e09b4e0b3640
Create Date: 2024-05-18 19:09:03.113908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0a4b92cc0b2a'
down_revision: Union[str, None] = 'e09b4e0b3640'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('official_id', sa.String(length=100), nullable=False),
    sa.Column('hash_password', sa.String(length=400), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('user_info', 'jwt_token')
    op.drop_column('user_info', 'jwt_expiration_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_info', sa.Column('jwt_expiration_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('user_info', sa.Column('jwt_token', sa.VARCHAR(length=400), autoincrement=False, nullable=True))
    op.drop_table('admin_info')
    # ### end Alembic commands ###
