"""Modifying the Admin and Creating Administration

Revision ID: ba0cb2aa6e62
Revises: d95db4650e77
Create Date: 2024-07-02 23:37:26.186797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba0cb2aa6e62'
down_revision: Union[str, None] = 'd95db4650e77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administrator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hash_password', sa.String(length=400), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('admin_info', sa.Column('name', sa.String(length=100), nullable=False))
    op.add_column('admin_info', sa.Column('location', sa.String(length=100), nullable=False))
    op.add_column('admin_info', sa.Column('contact', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_info', 'contact')
    op.drop_column('admin_info', 'location')
    op.drop_column('admin_info', 'name')
    op.drop_table('administrator')
    # ### end Alembic commands ###
