"""Adding Notification Feild In User

Revision ID: d95db4650e77
Revises: 0a4b92cc0b2a
Create Date: 2024-05-27 01:23:09.205742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd95db4650e77'
down_revision: Union[str, None] = '0a4b92cc0b2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_info', sa.Column('notifications', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_info', 'notifications')
    # ### end Alembic commands ###
